# when creating a kind cluster, run this config file
# sudo kind create cluster --config kind-config.yaml --name kind
# then docker can access the cluster at localhost:6443 / host.docker.internal:6443

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # apiServerAddress defaults to 127.0.0.1 which is accessible from host
  # and allows docker containers to access via host.docker.internal
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
      - localhost
      - 127.0.0.1
      - host.docker.internal
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
